#+TITLE:     L'écriture électroacoustique pour interface tangible
#+Author:    Martin Marier
#+EMAIL:     martin@martinmarier.com
#+DATE:      
#+DESCRIPTION:
#+KEYWORDS:
#+LANGUAGE:  fr
#+OPTIONS:   H:3 num:nil toc:nil \n:nil @:t ::t |:t ^:t -:t f:t *:t <:t
#+OPTIONS:   TeX:t LaTeX:t skip:nil d:nil todo:t pri:nil tags:not-in-toc
#+LaTeX_HEADER: \usepackage[comma, authoryear]{natbib}
#+LaTeX_HEADER: \usepackage{subfig}
#+LATEX_HEADER: \usepackage{hyperref}
#+LATEX_HEADER: \hypersetup{
#+LATEX_HEADER:     colorlinks,%
#+LATEX_HEADER:     citecolor=black,%
#+LATEX_HEADER:     filecolor=black,%
#+LATEX_HEADER:     linkcolor=blue,%
#+LATEX_HEADER:     urlcolor=black
#+LATEX_HEADER: }
#+LATEX_HEADER: \usepackage[french]{babel}
#+LATEX_HEADER: \usepackage[compact]{titlesec}

* Introduction
  Ce projet de thèse acomprend trois axes principaux: la conception d'une interface
  musicale, la conception de mappages pour cette interface, ainsi que la
  composition d'oeuvres électroacoustiques pour l'interface et les mappages
  conçus.

  Ladite interface est nommée l'/éponge/ et elle a l'allure d'un coussin rayé
  (voir figure \ref{fig:eponge}).  Des capteurs en détectent les déformations
  et un microcontrôleur achemine les données vers un ordinateur où les données
  sont mappées sur des paramètres de synthèse et de traitement sonore.  Ce
  dispositif permet l'interprétation de musiques électroacoustique devant
  public.
  
\begin{figure}
  \centering
  \subfloat[]{\label{fig:epongeDroite}
    \includegraphics[height=0.14\textheight]{figs/spongeDroite.jpg}}
  \subfloat[]{\label{fig:epongeHousse}
    \includegraphics[height=0.14\textheight]{figs/spongeDressed.jpg}}
  \subfloat[]{\label{fig:epongeGauche}
    \includegraphics[height=0.14\textheight]{figs/spongeGauche.jpg}}
  \caption{L'interface musicale conçue: l'éponge.  (a) Des capteurs et un microcontrôleur.  (b) L'éponge recouverte de sa housse rayée.  (c) D'autres capteurs.}
  \label{fig:eponge}
\end{figure}



* Étapes franchies  
** Conception de l'interface
   L'interface musicale développée (l'/éponge/) a fait l'objet d'une
   publication \citep{Marier2010} et a été utilisée régulièrement en concert
   depuis.  Elle continue de faire l'objet de modifications mineures, mais
   elle a atteint une certaine maturité et est un instrument très fiable et
   très expressif.

** Mappage
   Le mappage consiste à établir une correspondance entre les données des
   capteurs et les paramètres du son.  Il s'agit d'une étape très délicate qui
   soulève des questions fondamentales sur les nouvelles interfaces musicales
   et qui, par conséquent, se situe au coeur de ce projet de
   recherche-création.  De nombreuses stratégies de mappage ont été essayées
   en studio et testées devant public.  Une nouvelle techniques de mappage a
   été développée et a fait l'objet d'une publication \citep{Marier2012a}.  Un
   second article au sujet du mappage a été soumis au /Computer Music Journal/
   et pourrait être publié en 2014.

** Oeuvres
   Deux oeuvres pour éponge solo ont été créées et jouées à plusieurs reprises
   devant public: /Clarinette (Albino Butterfly)/ et /L'éloge du mou/.  Ces
   pièces partiellement improvisées évoluent et sont adaptées à chaque
   représentation et à chaque évoluation de l'instrument.  Un autre article au
   sujet du mappage, et du processus de création de ces oeuvres a été publié
   \cite{Marier2012}.
   

* Étapes prévues
  Le travail à accomplir avant le dépôt de la thèse comporte deux volets: la
  la composition d'une oeuvre pour deux éponges (un duo pour éponges) et la
  conduite d'une expérience qui implique des sujets qui essaieront l'éponge.

   
\bibliographystyle{francais}
\bibliography{/home/marierm/Documents/mendeley/library}
